## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999
matrix:
  allow_failures:
  - julia: nightly
script:
 - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
 - $TESTCMD -e 'Pkg.clone(pwd()); Pkg.build("ElectronDisplay"); Pkg.test("ElectronDisplay"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("ElectronDisplay")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
